apiVersion: skaffold/v3
metadata:
  name: vcluster
kind: Config
manifests:
  helm:
    releases:
      - name: '{{.GIT_USER}}'
        remoteChart: vcluster
        repo: https://charts.loft.sh
        namespace: '{{.GIT_USER}}'
        createNamespace: true
        setValues:
          vcluster.image: rancher/k3s:v1.23.5-k3s1
          mapServices.fromVirtual[0].from: istio-system/istio-ingressgateway
          mapServices.fromVirtual[0].to: customer-ingress
        setValueTemplates:
          syncer.extraArgs[0]: '--tls-san=cluster-{{.GIT_USER}}.ingress.cloudarmin.me'
          namespace: '{{.GIT_USER}}'
