apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    istio: ingressgateway # use the default IngressGateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
