---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config:
    domain:
      {{ printf "%s.%s" .Values.user .Values.ingress }}: ""
