---
# Source: argo-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: araminian-vcluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: araminian
    name: in-cluster
  project: default
  source:
    path: clusters/araminian/cluster
    repoURL: https://github.com/araminian/cluster-as-service.git
    targetRevision: HEAD
    directory:
      include: '{*.yaml,*.yml}'
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
